packages:
  - "config"
  - "packages/*"
  - "tests/*"
catalogs:
  typescript:
    typescript: ^7.0.2
  samchon:
    "@nestia/e2e": ^12.0.0
    ttsc: &ttsc ^0.19.0
    "@ttsc/lint": *ttsc
    "@ttsc/unplugin": *ttsc
    typia: &typia ^13.1.1
    "@typia/interface": *typia
    "@typia/mcp": *typia
  bundler:
    esbuild: ^0.25.12
  utils:
    "@types/node": ^22.18.0
    bumpp: ^10.4.0
    c8: ^10.1.3
    rimraf: ^6.0.1
