/** A source language a graph node can be declared in. */
export type GraphLanguage =
  | "typescript"
  | "javascript"
  | "go"
  | "rust"
  | "cpp"
  | "c"
  | "java"
  | "csharp"
  | "kotlin"
  | "swift"
  | "scala"
  | "zig"
  | "python"
  | "ruby"
  | "php"
  | "lua"
  | "bash"
  | "dart"
  | "unknown";
